PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/lib64,system/lib64)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/usr,system/usr)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/vendor,system/vendor)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/sony/tuba/framework,system/framework)
